### PR TITLE
set viewmode if share is readonly

### LINKED ISSUE #207: [BUG] UI let's users edit whiteboard on readonly share
### Steps to reproduce

* create whiteboard
* public share it via link
* open public share link
* click on the avatars in the top right corner

### expected behavior
* nothing happens

### actual behavior
edit bar with elements (arrow, square...) opens. User can edit the whiteboard, but nothing is synced to other clients or the backend

### PR DESCRIPTION
**Pull request by grnd-alt**
resolves #207

### CODE REVIEW

File: src/App.tsx [hunk 1]
```diff
@@ -45,15 +45,15 @@ export default function App({
...
-	const [viewModeEnabled] = useState(isEmbedded)
+	const [viewModeEnabled, setViewModeEnabled] = useState(isEmbedded)
 	const [zenModeEnabled] = useState(isEmbedded)
 	const [gridModeEnabled] = useState(false)
 
 	const isDarkMode = () => {
 		const ncThemes = document.body.dataset?.themes
 		return (
 			(window.matchMedia('(prefers-color-scheme: dark)').matches
-				&& (ncThemes === undefined || ncThemes?.indexOf('light') === -1))
```
Comment (juliushaertl) [inline src/App.tsx:56]: Reverting your previous fix? 😁

**Review by juliushaertl — CHANGES_REQUESTED** [review]

**Review by juliushaertl — APPROVED** [review]
